name: GH Actions for excerice 6 of chapter 11 from 'Python Testing with pytest'

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        
    steps:
      - uses: actions/checkout@v3
      - name: Installing Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and requested packages
        run: pip install tox
      - name: Run tox
        run: tox -e py